library(plyr)
library (data.table)
library(dplyr)
library(Hmisc)

files <- list.files(pattern="*.csv")

#this function takes microdata files named [Year].csv and adds the year as a column
read_csv_w_year <- function(x) {
  out <- read.csv(x)
  yr <- as.numeric(str_extract(x, "[A-Za-z0-9]{4}"))
  cbind(year=yr, out)
}

combined_files <- rbind.fill(lapply(files, read_csv_w_year))
combined_files_people <- rbind.fill(lapply(files, read_csv_w_year))

#Areas (PUMAs) to include/exclude in CoC
pre2011pumas <- c(301:307)
post2011pumas <- c(301:308)

#2011 and pre- use 2000 Census PUMAs. combined_files would be the dataframe from reading in the CSV generated by the snippet above
coc <- subset(combined_files, (combined_files$year <= 2011 & combined_files$PUMA %in% pre2011pumas) | (combined_files$year > 2011 & combined_files$PUMA %in% post2011pumas))
#for people level data (instead of households)
cocppl <- subset(combined_files_people, (combined_files_people$year <= 2011 & combined_files_people$PUMA %in% pre2011pumas) | (combined_files_people$year > 2011 & combined_files_people$PUMA %in% post2011pumas))

#this function allows you to cut a specific percentile from the microdata
percentiles <- function(df, year_col, tgt_col, weight_col, pctile){
  df %>% dplyr::filter(!is.na(get(tgt_col))) %>% dplyr::group_by(get(year_col)) %>%
    arrange(get(tgt_col)) %>%
    dplyr::mutate(cum_wt = cumsum(get(weight_col))) %>%
    dplyr::mutate(max_wt = max(cum_wt, na.rm = TRUE)) %>%
    dplyr::mutate(pct_dist = abs(cum_wt - (pctile*max_wt))) %>%
    dplyr::filter(pct_dist == min(pct_dist)) %>% arrange(get(year_col)) %>% ungroup(get(year_col)) %>%
    select(year_col, tgt_col)
}
View(format_for_excel(percentiles(coc,"year","GRNTP","WGTP",0.5),percentiles(coc,"year","GRNTP","WGTP",0.1),percentiles(coc,"year","GRNTP","WGTP",0.2)))

percentiles(coc,"year","GRNTP","WGTP",0.2)

format_for_excel <- function(x,y,z)
{
  cbind(x,y[,2],z[,2])
}

#get adult population
View(cocppl[cocppl$AGEP >= 18,] %>% dplyr::group_by(year) %>% dplyr::summarize(sum = sum(PWGTP)))
#get number of market units
View(coc[is.na(coc$VACS) | coc$VACS == 1 | coc$VACS == 3,] %>% dplyr::group_by(year) %>% dplyr::summarize(sum = sum(WGTP)))
