library(dplyr)

#Ignore - this snippet combined the raw PUMS response-level data 
# setwd("/Users/David/Documents/AHLA/pums/people")
# files <- list.files()
# 
# combined_files_people <- rbind.fill(lapply(files,fread))
# 
# write.csv(lacocppl, file = "pumsp0811_v2.csv")

#Areas (PUMAs) to include/exclude in LA CoC
excludedpuma <- c(3719,3718,3763,3765,3766,3769) ##unfortunately excludes Signal Hill, but what are you gonna do...
pre2011pumas <- setdiff(c(4500, 4600, 4700, 4800, 5100, 5200, 5300, 5401:6126), c(5701:5703, 6121)) ##2000 census PUMAs are 5401-6126 for LA County. Long Beach is 5701-5703. Glendale is 4900 and Pasadena is 5000 (excluded anyway). Since Signal Hill is thrown out of the post-2011 by necessity, so too must we throw it out of pre-2011 for consistency.
post2011pumas <- setdiff(3701:3769, excludedpuma)

#2011 and pre- use 2000 Census PUMAs. combined_files would be the dataframe from reading in the CSV generated by the snippet above
lacoc4 <- subset(combined_files, (combined_files$YEAR <= 2011 & combined_files$PUMA %in% pre2011pumas) | (combined_files$YEAR > 2011 & combined_files$PUMA %in% post2011pumas))
lacocppl <- subset(combined_files_people, (combined_files_people$year <= 2011 & combined_files_people$PUMA %in% pre2011pumas) | (combined_files_people$year > 2011 & combined_files_people$PUMA %in% post2011pumas))

#cutting percentiles
percentiles <- function(df, year_col, tgt_col, weight_col, pctile){
  df %>% dplyr::group_by(get(year_col)) %>%
    arrange(get(tgt_col)) %>%
    dplyr::mutate(cum_wt = cumsum(get(weight_col))) %>%
    dplyr::mutate(max_wt = max(cum_wt, na.rm = TRUE)) %>%
    dplyr::mutate(pct_dist = abs(cum_wt - (pctile*max_wt))) %>%
    dplyr::filter(pct_dist == min(pct_dist)) %>% arrange(get(year_col)) %>% ungroup(get(year_col)) %>%
    select(year_col, tgt_col)
}
percentiles(lacoc4,"YEAR","HINCP","WGTP",0.5)
